"""
Django settings for flashnacks project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

# -----------------------------
# Rutas base
# -----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------
# Seguridad
# -----------------------------
SECRET_KEY = 'django-insecure--i+wnlkm6m-lhi@d69q+388n+(u8)^+2!&1uip*03&co*h#8ur'

# DEBUG True para desarrollo, False para producción
DEBUG = True

# Ajusta según tu dominio en producción
ALLOWED_HOSTS = ["santisn.pythonanywhere.com", "localhost", "127.0.0.1"]


# -----------------------------
# Apps instaladas
# -----------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  # nuestra app principal
]

# -----------------------------
# Middleware
# -----------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------
# URLs y WSGI
# -----------------------------
ROOT_URLCONF = 'flashnacks.urls'

WSGI_APPLICATION = 'flashnacks.wsgi.application'

# -----------------------------
# Templates
# -----------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Carpeta global de templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -----------------------------
# Base de datos (SQLite por defecto)
# -----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------
# Validación de contraseñas
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -----------------------------
# Internacionalización
# -----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -----------------------------
# Archivos estáticos
# -----------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Donde se recopilan los static files para producción
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Carpeta para tus static files propios (css, js, img)
]

# -----------------------------
# Archivos media (si subes imágenes)
# -----------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------------
# Tipo de clave primaria por defecto
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
